name: Get Repo Info

# Run every night at midnight
# on:
  # schedule:
    # - cron: '0 0 * * *'
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get-info-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.5.1'

      - name: Install deps
        run: |
          npm install @actions/core
          npm install @actions/github
          npm install utf8

      - name: Get Repo Info
        run: node src/lib/scripts/GetRepoInfo.js ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Repo Changes
        run: |
          git remote set-url --push origin https://q2d2:$GITHUB_TOKEN@github.com/Oddant1/library-svelte
          git config --local user.email "q2d2.noreply@gmail.com"
          git config --local user.name "q2d2"
          git add .
          git commit -m "Updated Repo Info"
          git push
